apiVersion: skaffold/v3
kind: Config
metadata:
  name: tyr-java-service
build:
  artifacts:
    - image: tyr-java-service
profiles:
  - name: dev
    deploy:
      cloudrun:
        projectid: dev-services-tyrconsulting
        region: us-central1
        service: tyr-java-service
  - name: stage
    deploy:
      cloudrun:
        projectid: stage-services-tyrconsulting
        region: us-central1
        service: tyr-java-service
  - name: prod
    deploy:
      cloudrun:
        projectid: prod-services-tyrconsulting
        region: us-central1
        service: tyr-java-service
